// Bundles Yjs + the Hocuspocus provider into ONE classic <script> file that the
// frontend can load with no build step of its own.
//
// The rest of static/ is deliberately build-free: index.html loads plain
// non-module scripts, `python server.py` serves the folder as-is, and the
// GitHub Pages workflow just uploads it. Yjs only ships as ES modules, so this
// is the one place a bundler is unavoidable — and its output is COMMITTED to
// static/vendor/ so that property survives.
//
// Regenerate after changing the pinned versions in package.json:
//
//     cd collab && npm install && npm run build
//
// Output: static/vendor/collab-bundle.js, exposing window.FaaglarnaYjs.

import { build } from 'esbuild';
import { mkdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outfile = join(here, '..', 'static', 'vendor', 'collab-bundle.js');

mkdirSync(dirname(outfile), { recursive: true });

await build({
  stdin: {
    contents: `
      export * as Y from 'yjs';
      export { HocuspocusProvider } from '@hocuspocus/provider';
    `,
    resolveDir: here,
    loader: 'js',
  },
  outfile,
  bundle: true,
  minify: true,
  sourcemap: false,
  // IIFE + a global name keeps it a classic script, matching how index.html
  // already loads fountain.js / pagination.js / app.js / backend.js.
  format: 'iife',
  globalName: 'FaaglarnaYjs',
  target: ['es2020'],
  legalComments: 'none',
  banner: {
    js: '/* Generated by collab/build.mjs - do not edit. Yjs + Hocuspocus provider (MIT). */',
  },
});

const kb = (statSync(outfile).size / 1024).toFixed(1);
console.log(`wrote static/vendor/collab-bundle.js (${kb} kB)`);
